development:
  adapter: postgresql
  encoding: utf8
  database: blog_development
  pool: 5
  username: vp032599
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: project_test
  pool: 5
  username: vp032599
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: project_production
  pool: 5
  username: vp032599
  password:
